### ISSUE TITLE
Publish on npm/bower?

### ISSUE THREAD

**Issue by cjpatoilo** [lazaronixon/sass-zero#1]
Consider publishing on npm (maybe bower as well?) so we can manage versions using standard tools.

**Comment by cjpatoilo** [comment]
@lazaronixon I can help you with that. 

To publish a scoped package with public visibility, use `npm publish --access public`.

1. On the command line, navigate to the root directory of your **package**. cd /path/to/**package**.
1. To publish your scoped public **package** to the **npm** registry, run: `npm publish --access public`.

https://zellwk.com/blog/publish-to-npm/

**Comment by lazaronixon** [comment]
Muito obrigado pelo interesse. O trabalho que você fez com o milligram é excelente. A minha necessidade aqui era uma biblioteca para rails, porem  eu estava olhando o código do bootstrap e vi que ele compartilha rubygem e npm, mais tarde vou ver as alterações que precisam serem feitas para acomodar os dois ambientes.
